name: LADevops
on:
 push:
   branches: master
 workflow_dispatch:

jobs:
  CI:
    name: CI
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0
      - name: action-zip
        uses: byteever/action-build-zip@master
        with:
          filename: 'release.zip'
      
     
   
