name: LADevops
on:
 push:
   branches: main
 workflow_dispatch:

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: action-zip
        uses: vimtor/action-zip@v1
        with:
          files: ./
          dest: release.zip
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
            path: release.zip
     
   
