name: LADevops
on:
 push:
   branches: main
 workflow_dispatch:
 
env:
   ResourceGroup: Demo
   AppName: GithubDevops

jobs:
  CI_Workflow:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: action-zip
        uses: vimtor/action-zip@v1
        with:
          files: ./
          dest: release.zip
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
            name: build-artifact
            path: release.zip
  CD_Workflow:
     name: CD
     needs: CI_Workflow
     runs-on: ubuntu-latest
     steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
           creds: ${{secrets.AZURE_CREDENTIALS}}
           enable-AzPSSession: true
      - name: Azure PowerShell Action
        id: laapp
        uses: Azure/powershell@v1
        with:
          inlineScript: |
            $profile = Get-AzWebAppPublishingProfile `
              -ResourceGroupName ${{env.ResourceGroup}} `
              -Name ${{env.AppName}}
            $profile = $profile.Replace("`r", "").Replace("`n", "")
            Write-Output "::set-output name=profile::$profile"
          azPSVersion: latest
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
         name: build-artifact
         path: release.zip
      - name: Azure Functions Action
        uses: Azure/functions-action@v1.4.7
        with:
           app-name: $AppName
           package: release.zip
           publish-profile: ${{steps.laapp.outputs.profile}}
           
        
        
     
   
